on:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    # Add path to production site example:
     - run: curl -f https://interview-prep-coach-jkjyperfibx48rdnprzxhn.streamlit.app/