on:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    # Add path to production site example:
    # - run: curl -f https://practical-interview-preparation.streamlit.app/